# Generated by Django 2.1.1 on 2018-09-15 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clip',
            name='end_time',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='clip',
            name='start_time',
            field=models.CharField(max_length=5),
        ),
    ]
