# Generated by Django 2.1.1 on 2018-09-15 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_auto_20180915_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
