# Generated by Django 2.1.1 on 2018-09-15 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_mediaitem_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clip',
            name='end_time',
            field=models.CharField(default='00:00', max_length=5),
        ),
        migrations.AlterField(
            model_name='clip',
            name='start_time',
            field=models.CharField(default='00:00', max_length=5),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='type',
            field=models.TextField(choices=[('youtube', 'Youtube Video'), ('audio', 'Audio')], default='youtube'),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='youtube_id',
            field=models.CharField(default='', max_length=200),
        ),
    ]
