# Generated by Django 2.1.1 on 2018-09-15 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_auto_20180915_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaitem',
            name='url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='youtube_id',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
