# Generated by Django 2.1.1 on 2018-09-16 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0006_auto_20180915_2225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediaitem',
            old_name='url',
            new_name='resource_url',
        ),
    ]
