# Generated by Django 2.1.1 on 2018-09-24 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0007_auto_20180916_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clip',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='clip',
            name='start_time',
        ),
        migrations.AddField(
            model_name='clip',
            name='end_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clip',
            name='end_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clip',
            name='end_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clip',
            name='start_hours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clip',
            name='start_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='clip',
            name='start_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='clip',
            name='media_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clips', to='rest_api.MediaItem'),
        ),
    ]
